apiVersion: v1
kind: Pod
metadata:
  name: product-catalog-module
  labels:
    app: product-catalog-module
spec:
  containers:
    - name: product-catalog-module
      image: 339712975523.dkr.ecr.us-east-1.amazonaws.com/product-catalog-module:latest
      ports:
        - containerPort: 8080
